### ISSUE TITLE
Minor UI issue on 

### ISSUE THREAD

**Issue by The-Lone-Druid** [The-Lone-Druid/DoseMate#2]
![image](https://github.com/The-Lone-Druid/DoseMate/assets/53161242/c66483ba-6bca-4da5-8356-b6a873bb0698)

@azhar-siddiqui I've encountered a small issue, can you have a look?

**Comment by azhar-siddiqui** [comment]
resolve

**Comment by The-Lone-Druid** [comment]
@azhar-siddiqui do raise the PR for the same.
